### ISSUE TITLE
Get an exception when running...

### ISSUE THREAD

**Issue by fullphat** [repraze/unicorn-clock#1]
Edit:

I fixed the font error by moving resources/* into src/resources/ but I still get an error:

```
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at framework.Animator.run(Animator.java:62)
	at UnicornClock.main(UnicornClock.java:43)
```

I'm launching the app using SSH and there's no monitor connected to the Pi - not sure if that's an issue?

**Comment by repraze** [comment]
I think this is due to the fact that you are running it in test mode
`animator.setTestMode(true);`
This allows you to run the code of your PC to see what would happen.
